vervices:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - nvidia-rag
networks:
  nvidia-rag:
    external: true

